---
apiVersion: xl-deploy/v1
kind: Applications
spec:
- directory: Applications/PetClinic

---
apiVersion: xl-deploy/v1
kind: Applications
spec:
  - name: Applications/PetClinic/PetClinic
    type: udm.Application
    children:
      - name: "1.0"
        type: udm.DeploymentPackage
        orchestrator:
          - parallel-by-dependency
        undeployDependencies: true
        deployables:
          - name: pet-clinic
            type: k8s.ResourcesFile
            file: !file "manifests/petclinic-service.yaml"
